Has iniciado sesion.
<a href="logout/">Salir</a>

<h1>Usuarios</h1>
<p>
<?php foreach ($usuarios as $value) {
     echo $value->getUserId().' - ';
     echo $value->getUsername().'<br />';
}?>
</p>

<h1>Foros</h1> 
<p>
<?php foreach ($foros as $value) {
     echo $value->getForumTitle();     
}?>
</p>

<h1>Usuarios 2</h1>
<p>
<?php foreach ($usuarios2 as $value) {
     echo $value->getUserId().' - ';
     echo $value->getUsername().'<br />';
}?>
</p>
