<?php
// This file generated by Propel 1.5.6 convert-conf target
// from XML runtime conf file /var/www/propel/proyectos/dokeos/runtime-conf.xml
$prefijo = '';

if(Session::has('myDbName')){
    $myDbName = $prefijo.Session::get('myDbName');
}else{
    $myDbName = $prefijo.'dokeos_main';
}
$conf = array (
  'datasources' => 
  array (
    'dokeos' => 
    array (
      'adapter' => 'mysql',
      'connection' => 
      array (
        'dsn' => "mysql:host=localhost;dbname=$myDbName",
        'user' => 'root',
        'password' => 'root',
      ),
    ),
    'default' => 'dokeos',
  ),
  'generator_version' => '1.5.6',
);
$conf['classmap'] = include(dirname(__FILE__) . DIRECTORY_SEPARATOR . 'classmap-dokeos-conf.php');
return $conf;
